#!/usr/bin/python"
# -*- coding: utf-8 -*-
#: kivy 1.9.1

<CharacterLabel>:
    size_hint_y: None
    height: "40dp"
    text: "Character"
    canvas.before:
        Color:
            rgba: 1, 0, 0, 0.1
        Rectangle:
            pos: self.pos
            size: self.size

<CharacterView>:
    GridLayout:
        id: grid
        cols: 1
        height: "70dp"
        spacing: 10
        padding: 10
        size_hint_y: None